namespace Grupo6.Data.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class FixAllForeignKey_Migration : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.ItemCarrito", "Carrito_Id", "dbo.Carrito");
            DropForeignKey("dbo.Carrito", "Usuario_Id", "dbo.Usuario");
            DropForeignKey("dbo.ItemCarrito", "Producto_Id", "dbo.Producto");
            DropForeignKey("dbo.Producto", "CategoriaProducto_Id", "dbo.CategoriaProducto");
            DropForeignKey("dbo.DetalleFactura", "Producto_Id", "dbo.Producto");
            DropForeignKey("dbo.DetalleFactura", "Factura_Id", "dbo.Factura");
            DropForeignKey("dbo.Despacho", "Factura_Id", "dbo.Factura");
            DropForeignKey("dbo.Factura", "Usuario_Id", "dbo.Usuario");
            DropForeignKey("dbo.Despacho", "Estado_Id", "dbo.EstadoPedido");
            DropForeignKey("dbo.Direccion", "Usuario_Id", "dbo.Usuario");
            DropIndex("dbo.Carrito", new[] { "Usuario_Id" });
            DropIndex("dbo.ItemCarrito", new[] { "Carrito_Id" });
            DropIndex("dbo.ItemCarrito", new[] { "Producto_Id" });
            DropIndex("dbo.Producto", new[] { "CategoriaProducto_Id" });
            DropIndex("dbo.DetalleFactura", new[] { "Factura_Id" });
            DropIndex("dbo.DetalleFactura", new[] { "Producto_Id" });
            DropIndex("dbo.Factura", new[] { "Usuario_Id" });
            DropIndex("dbo.Despacho", new[] { "Estado_Id" });
            DropIndex("dbo.Despacho", new[] { "Factura_Id" });
            DropIndex("dbo.Direccion", new[] { "Usuario_Id" });
            DropColumn("dbo.Carrito", "IdUsuario");
            DropColumn("dbo.ItemCarrito", "IdPedido");
            DropColumn("dbo.ItemCarrito", "IdProducto");
            DropColumn("dbo.Producto", "IdCategoriaProducto");
            DropColumn("dbo.DetalleFactura", "IdProducto");
            DropColumn("dbo.Factura", "IdUsuario");
            DropColumn("dbo.Despacho", "NroFactura");
            DropColumn("dbo.Despacho", "IdEstadoPedido");
            DropColumn("dbo.Direccion", "IdUsuario");
            RenameColumn(table: "dbo.ItemCarrito", name: "Carrito_Id", newName: "IdPedido");
            RenameColumn(table: "dbo.Carrito", name: "Usuario_Id", newName: "IdUsuario");
            RenameColumn(table: "dbo.ItemCarrito", name: "Producto_Id", newName: "IdProducto");
            RenameColumn(table: "dbo.Producto", name: "CategoriaProducto_Id", newName: "IdCategoriaProducto");
            RenameColumn(table: "dbo.DetalleFactura", name: "Producto_Id", newName: "IdProducto");
            RenameColumn(table: "dbo.DetalleFactura", name: "Factura_Id", newName: "NroFactura");
            RenameColumn(table: "dbo.Despacho", name: "Factura_Id", newName: "NroFactura");
            RenameColumn(table: "dbo.Factura", name: "Usuario_Id", newName: "IdUsuario");
            RenameColumn(table: "dbo.Despacho", name: "Estado_Id", newName: "IdEstadoPedido");
            RenameColumn(table: "dbo.Direccion", name: "Usuario_Id", newName: "IdUsuario");
            AlterColumn("dbo.Carrito", "IdUsuario", c => c.Int(nullable: false));
            AlterColumn("dbo.ItemCarrito", "IdPedido", c => c.Int(nullable: false));
            AlterColumn("dbo.ItemCarrito", "IdProducto", c => c.Int(nullable: false));
            AlterColumn("dbo.Producto", "IdCategoriaProducto", c => c.Int(nullable: false));
            AlterColumn("dbo.DetalleFactura", "NroFactura", c => c.Int(nullable: false));
            AlterColumn("dbo.DetalleFactura", "IdProducto", c => c.Int(nullable: false));
            AlterColumn("dbo.Factura", "IdUsuario", c => c.Int(nullable: false));
            AlterColumn("dbo.Despacho", "IdEstadoPedido", c => c.Int(nullable: false));
            AlterColumn("dbo.Despacho", "NroFactura", c => c.Int(nullable: false));
            AlterColumn("dbo.Direccion", "IdUsuario", c => c.Int(nullable: false));
            CreateIndex("dbo.Carrito", "IdUsuario");
            CreateIndex("dbo.ItemCarrito", "IdPedido");
            CreateIndex("dbo.ItemCarrito", "IdProducto");
            CreateIndex("dbo.Producto", "IdCategoriaProducto");
            CreateIndex("dbo.DetalleFactura", "NroFactura");
            CreateIndex("dbo.DetalleFactura", "IdProducto");
            CreateIndex("dbo.Factura", "IdUsuario");
            CreateIndex("dbo.Despacho", "NroFactura");
            CreateIndex("dbo.Despacho", "IdEstadoPedido");
            CreateIndex("dbo.Direccion", "IdUsuario");
            AddForeignKey("dbo.ItemCarrito", "IdPedido", "dbo.Carrito", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Carrito", "IdUsuario", "dbo.Usuario", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ItemCarrito", "IdProducto", "dbo.Producto", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Producto", "IdCategoriaProducto", "dbo.CategoriaProducto", "Id", cascadeDelete: true);
            AddForeignKey("dbo.DetalleFactura", "IdProducto", "dbo.Producto", "Id", cascadeDelete: true);
            AddForeignKey("dbo.DetalleFactura", "NroFactura", "dbo.Factura", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Despacho", "NroFactura", "dbo.Factura", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Factura", "IdUsuario", "dbo.Usuario", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Despacho", "IdEstadoPedido", "dbo.EstadoPedido", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Direccion", "IdUsuario", "dbo.Usuario", "Id", cascadeDelete: true);
            DropColumn("dbo.DetalleFactura", "Letra");
            DropColumn("dbo.DetalleFactura", "Numero");
        }
        
        public override void Down()
        {
            AddColumn("dbo.DetalleFactura", "Numero", c => c.Int(nullable: false));
            AddColumn("dbo.DetalleFactura", "Letra", c => c.String());
            DropForeignKey("dbo.Direccion", "IdUsuario", "dbo.Usuario");
            DropForeignKey("dbo.Despacho", "IdEstadoPedido", "dbo.EstadoPedido");
            DropForeignKey("dbo.Factura", "IdUsuario", "dbo.Usuario");
            DropForeignKey("dbo.Despacho", "NroFactura", "dbo.Factura");
            DropForeignKey("dbo.DetalleFactura", "NroFactura", "dbo.Factura");
            DropForeignKey("dbo.DetalleFactura", "IdProducto", "dbo.Producto");
            DropForeignKey("dbo.Producto", "IdCategoriaProducto", "dbo.CategoriaProducto");
            DropForeignKey("dbo.ItemCarrito", "IdProducto", "dbo.Producto");
            DropForeignKey("dbo.Carrito", "IdUsuario", "dbo.Usuario");
            DropForeignKey("dbo.ItemCarrito", "IdPedido", "dbo.Carrito");
            DropIndex("dbo.Direccion", new[] { "IdUsuario" });
            DropIndex("dbo.Despacho", new[] { "IdEstadoPedido" });
            DropIndex("dbo.Despacho", new[] { "NroFactura" });
            DropIndex("dbo.Factura", new[] { "IdUsuario" });
            DropIndex("dbo.DetalleFactura", new[] { "IdProducto" });
            DropIndex("dbo.DetalleFactura", new[] { "NroFactura" });
            DropIndex("dbo.Producto", new[] { "IdCategoriaProducto" });
            DropIndex("dbo.ItemCarrito", new[] { "IdProducto" });
            DropIndex("dbo.ItemCarrito", new[] { "IdPedido" });
            DropIndex("dbo.Carrito", new[] { "IdUsuario" });
            AlterColumn("dbo.Direccion", "IdUsuario", c => c.Int());
            AlterColumn("dbo.Despacho", "NroFactura", c => c.Int());
            AlterColumn("dbo.Despacho", "IdEstadoPedido", c => c.Int());
            AlterColumn("dbo.Factura", "IdUsuario", c => c.Int());
            AlterColumn("dbo.DetalleFactura", "IdProducto", c => c.Int());
            AlterColumn("dbo.DetalleFactura", "NroFactura", c => c.Int());
            AlterColumn("dbo.Producto", "IdCategoriaProducto", c => c.Int());
            AlterColumn("dbo.ItemCarrito", "IdProducto", c => c.Int());
            AlterColumn("dbo.ItemCarrito", "IdPedido", c => c.Int());
            AlterColumn("dbo.Carrito", "IdUsuario", c => c.Int());
            RenameColumn(table: "dbo.Direccion", name: "IdUsuario", newName: "Usuario_Id");
            RenameColumn(table: "dbo.Despacho", name: "IdEstadoPedido", newName: "Estado_Id");
            RenameColumn(table: "dbo.Factura", name: "IdUsuario", newName: "Usuario_Id");
            RenameColumn(table: "dbo.Despacho", name: "NroFactura", newName: "Factura_Id");
            RenameColumn(table: "dbo.DetalleFactura", name: "NroFactura", newName: "Factura_Id");
            RenameColumn(table: "dbo.DetalleFactura", name: "IdProducto", newName: "Producto_Id");
            RenameColumn(table: "dbo.Producto", name: "IdCategoriaProducto", newName: "CategoriaProducto_Id");
            RenameColumn(table: "dbo.ItemCarrito", name: "IdProducto", newName: "Producto_Id");
            RenameColumn(table: "dbo.Carrito", name: "IdUsuario", newName: "Usuario_Id");
            RenameColumn(table: "dbo.ItemCarrito", name: "IdPedido", newName: "Carrito_Id");
            AddColumn("dbo.Direccion", "IdUsuario", c => c.Int(nullable: false));
            AddColumn("dbo.Despacho", "IdEstadoPedido", c => c.Int(nullable: false));
            AddColumn("dbo.Despacho", "NroFactura", c => c.Int(nullable: false));
            AddColumn("dbo.Factura", "IdUsuario", c => c.Int(nullable: false));
            AddColumn("dbo.DetalleFactura", "IdProducto", c => c.Int(nullable: false));
            AddColumn("dbo.Producto", "IdCategoriaProducto", c => c.Int(nullable: false));
            AddColumn("dbo.ItemCarrito", "IdProducto", c => c.Int(nullable: false));
            AddColumn("dbo.ItemCarrito", "IdPedido", c => c.Int(nullable: false));
            AddColumn("dbo.Carrito", "IdUsuario", c => c.Int(nullable: false));
            CreateIndex("dbo.Direccion", "Usuario_Id");
            CreateIndex("dbo.Despacho", "Factura_Id");
            CreateIndex("dbo.Despacho", "Estado_Id");
            CreateIndex("dbo.Factura", "Usuario_Id");
            CreateIndex("dbo.DetalleFactura", "Producto_Id");
            CreateIndex("dbo.DetalleFactura", "Factura_Id");
            CreateIndex("dbo.Producto", "CategoriaProducto_Id");
            CreateIndex("dbo.ItemCarrito", "Producto_Id");
            CreateIndex("dbo.ItemCarrito", "Carrito_Id");
            CreateIndex("dbo.Carrito", "Usuario_Id");
            AddForeignKey("dbo.Direccion", "Usuario_Id", "dbo.Usuario", "Id");
            AddForeignKey("dbo.Despacho", "Estado_Id", "dbo.EstadoPedido", "Id");
            AddForeignKey("dbo.Factura", "Usuario_Id", "dbo.Usuario", "Id");
            AddForeignKey("dbo.Despacho", "Factura_Id", "dbo.Factura", "Id");
            AddForeignKey("dbo.DetalleFactura", "Factura_Id", "dbo.Factura", "Id");
            AddForeignKey("dbo.DetalleFactura", "Producto_Id", "dbo.Producto", "Id");
            AddForeignKey("dbo.Producto", "CategoriaProducto_Id", "dbo.CategoriaProducto", "Id");
            AddForeignKey("dbo.ItemCarrito", "Producto_Id", "dbo.Producto", "Id");
            AddForeignKey("dbo.Carrito", "Usuario_Id", "dbo.Usuario", "Id");
            AddForeignKey("dbo.ItemCarrito", "Carrito_Id", "dbo.Carrito", "Id");
        }
    }
}
