//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grupo6.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrito
    {
        public int IdPedido { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime Creado { get; set; }
        public Nullable<System.DateTime> Modificado { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ItemCarrito ItemCarrito { get; set; }
    }
}
